# Generated by Django 5.2.6 on 2026-01-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('necta_number', models.CharField(blank=True, help_text='Required for Form II, Form III, and Form IV only', max_length=20, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField()),
                ('form', models.IntegerField(choices=[(1, 'Form I'), (2, 'Form II'), (3, 'Form III'), (4, 'Form IV')])),
                ('stream', models.CharField(max_length=5)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_contact', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
