from django.core.management.base import BaseCommand
from students.models import Student
from datetime import date

class Command(BaseCommand):
    help = "Import fixed list of Form One A students (all names in capital letters)"

    def handle(self, *args, **kwargs):
        names = [
            
            # form IV students
            "ARAFA MOHAMEDI BEYA",
            "ASMAA HUSSEIN ATHUMANI",
            "AZINATU SAIDI HASSANI",
            "AZIZA JUMA TOYO",
            "BATHRETH PETER LUVANDA",
            "BIHAWA ALLY MASANGU",
            "FARIDA HASSANI KATANGA",
            "FAUDHIA MUSA SWALEHE",
            "HIDAYA OMARY JUMA",
            "HUSNA HUSSEIN MOHAMEDI",
            "JAUZA ABDALA ITASO",
            "JAZILA IDDI HUSSEIN",
            "KULUTHUMU ABDALA ISSA",
            "MARIAMU AMOSI CHORACHORA",
            "MWAJUMA IDDI ABDALA",
            "NADHIFA SALUMU HUSSENI",
            "NAJATI HAMZA RAMADHANI",
            "NAJATI KIRO KIPUNDE",
            "NAJMA SELEMANI IDDI",
            "NARMA YUSUFU SEIFU",
            "NASMA JUMA TAI",
            "NASRA ABDALA HASSANI",
            "NASRA HASSANI RAMADHANI",
            "NUFAILA HABIBU ALLY",
            "RAHMA MUHAMEDI ABEDI",
            "RAHMA SWALEHE KUPA",
            "REHEMA JUMA YOHANA",
            "SABAHA SALUMU ATAKACHO",
            "SABRINA RAJABU RAMADHANI",
            "SAKINA ALEX PETRO",
            "SALMA ABDI ATHUMANI",
            "SALOME KIDABARASA KINYANGI",
            "SHAWARI SAIDI GAU",
            "SWAHIBA HERI IDDI",
            "UM-SALAMA ABDI KIPOTO",
            "ZAKIA SWAHIBU HATIBU",
            "ZAWIA IDRISA SINGIDA",
            "ZULHATI ALLY TUNGU",
            "ZUWENA MASARE MASUDI",
            "SALMA MUHAMEDI BEYA",
            "ABBAKARI OMARY HUSSEIN",
            "ABDULI-KARIMU AYUBU GUFU",
            "ABDULI TWAHA NDULA",
            "AMRANI BASHIRU MADUNGA",
            "BILALI JUMA MAULIDI",
            "BILALI MAULIDI HONDO",
            "DOKTA ABDI WINTO",
            "HAJI HARUNA HASSANI",
            "IBRAHIMU MAULIDI SOMA",
            "IDDI RAAMADHANI OMARY",
            "LUKUMANI KASSIMU KIRO",
            "MALKI SIRAJI MAULIDI",
            "MUHAMEDI BAKARI OMARY",
            "MUHAMEDI MUSA NOTI",
            "NAJIMU RAMADHANI JUMA",
            "RAMIA SHABANI LONDISA",
            "SALUMU KASSIMU JUMA ",
            "SALUMU ALLY ABDULI",
            "SHABANI KASIMU SHABANI",
            "YASRI SHABANI BAKARI",
            "YAZIDU BASHIRU BAKARI",
            "SHABANI ABDI JUMA",
            
            # form II A students
            
            # "ABDULAZIZI JUMANE MASARE",
            # "ANUWAR RAMADHANI ALLY",
            # "NAJMA IDDI NORI",
            # "MULHATI MIRAJ MAFITA",
            # "RAHMA HARUNA LOTA",
            # "MARIAMU ISMAIL ISSA",
            # "HAJATI SHABANI MOHAMEDI",
            # "MARIAMU MOHAMEDI SAIDI",
            # "SHAMILA SWALEHE BAKARI",
            # "MHAMAD SUMA MSURI",
            # "ZAIDINA IJIMBO SAIDI",
            # "MULHATI SAIDII ISSA",
            # "SALUMU ABDALLAH SAID",
            # "SHADIA SWAHIBU HATIBU",
            # "SAMIRA YAKUBU HASSANI",
            # "SABRINA JUMA TAI",
            # "HIJRA SUDI MSAFIRI",
            # "NADIA RASHID KIDUNDA",
            # "AISHA SAIDI KONYO",
            # "SUMAIYA HASANI ATHUMANI",
            # "SANIA SALUMU HALIFA",
            # "AZIZA HASSAN NYORITO",
            # "ZAKIA MASHAKA HASSANI",
            # "SUHAILA HUSSEIN IDDI",
            # "NASMA SWALEHE KUPA",
            # "ALLY HAMADI SOLOKA",
            # "BEZANUNI JUMA IDALA",
            # "ANNA MUNGURI JOSEPH",
            # "SALMA JUMA KEYA",
            # "HASHRA SALUMU HUSENI",
            # "HASSANI SAIDY TEMBO",
            # "LATIFA MUSA SWALEHE",
            # "AVERINA ANDREA DAFI",
            # "CATHERINI ANDREA DAFI",
            # "AL-HADI HASANI IDDI",
            # "RAZAKI ISSA KIDUKA",
            # "NANCY SANJI RICHARD", 
            
            
            # form II B students 
            # "AMINA MZAMILO RAMADHANI",
            # "ASMAA WAZIRI HAMISI",
            # "HASANATI HASHIMU KIMOLO",
            # "HAFSA ALLY MUSHANI",
            # "HANU TOMASI AMA",
            # "HADIA JONGO HATIBU",
            # "HADIJA HAJI RAMADHANI",
            # "HAWA HUSENI RASHIDI",
            # "HAZLA YUNUSU IDDI",
            # "JIDAWI HALIFA SAIDI",
            # "KULUTHUMU RUBENI ANDASONI",
            # "LUTUFIA NURUDINI HUSSENI",
            # "MUZDALFA JUMA IDDI",
            # "MAIZARA ISMAILI JUMANNE",
            # "NAJIA RAMADHANI ATHUMANI",
            # "NAIMA HAMISI IDDI",
            # "NASMA SHABANI BUNDA",
            # "SABRINA SHABANI KEYA",
            # "SABRINA JUMA SAIDI",
            # "SUMAIYA MOHAMMEDI SAIDI",
            # "SUMAIYA SEPHU JUMA",
            # "SHAMSIA ISSA ATHUMANI",
            # "SHINAIDA TWAHA RAMADHANI",
            # "UDHIWAIYA SELEMANI HUSENI",
            # "ZULFA RASHIDI IDDI",
            # "ZULATI IBRAHIMU CHUKA",
            # "AHMEDI ABDALA RASHIDI",
            # "ALHAJI JUMA ABDALAHI",
            # "ABUMAIS MOHAMEDI ATHUMANI",
            # "ABDUL RAMADHANI SAIDI",
            # "ADAMU ALLY RAMADHANI",
            # "ALLY RAMADHANI HAMISI",
            # "NASRI ALLY HUSSEN",
            # "ABDALA ABDULAHI TAI",
            # "FAHIKA HAMIS BUKUTU",
            # "SURAIYA HASSANI MCHANA",
            # "JAUREJI OMARI FUNDI",
            # "FARAJA WILSON NDAHANI",
            # "SHURAIFA ISRAFILI IBRAHIMU",
            # "TWALHIYA OMARI JUMA",
            # "IKRAM ELIYASA RAMADHAN",
            # "NASRA SWALEHE KUPA",
            # "SUDAISI ALLY HERI",
            # "SHAFII IDDI NDWATA",
            # "SHABANI ABDALA KIMOLO",
            # "IJUMAA HAMZA SHABANI",
            # "HADIJA ABDALA HASSANI",
            # "NASRA IDDI GENDA",
            # "NASRA MDEKE HUSENI",
            # "REBEKA SAMWELI IBRAHIMU",
            # "SALMA RAJABU ISSA",
            # "SAUMU YUSUPH SHABANI",
            # "SHARIFA OMARI HAMISI",
            # "LATIFA YAHAYA IDDI",
            # "ZAHARA IDDI HAMISI",
            # "SWAUMU YUSUPH SHABANI"
            
            # form III-A students
            # "NADHIFA MAIDI HUSENI",
            # "MARIAMU KASSIMU YUSUPH",
            # "AZNATU JUMA IDDI",
            # "HAIRATI AYUBU GUFU",
            # "HAMIDA HASSANI ATHUMANI",
            # "HAJIRUNA BASHIRU HUSENI",
            # "HAWA JUMANNE YUBA",
            # "NASMA HAMISI ALLY",
            # "NADHIFA HASANI JUMA",
            # "MUZDALFA ABDUL-BASTI TWAHA",
            # "NADIA MOHAMEDI HAMIDU",
            # "SALMA RASHIDI KAKU",
            # "SAUMU SHABANI NDULA",
            # "SAMIA RAMADHANI LUBUVA",
            # "TASLIMA ABEDI SALUMU",
            # "TWALATI YASINI MOHAMEDI",
            # "THUWAIBA SHABANI MOHAMEDI",
            # "ZAHARA JUMA MAULIDI",
            # "ZILIZALA MOHAMEDI ALLY",
            # "ZALHA YUSUPH MADUKA",
            # "ZUBEDA MOHAMEDI ATHUMANI",
            # "ZALFZINA SHAIBU RAMADHANI",
            # "RUKAIYA BAKARI ALLY",
            # "SUMAIYA RAMADHANI ALLY",
            # "NASMA ALLY ILUNDU",
            # "ASNATI RASHIDI ALLY",
            # "BUSWAINA AMANI NOTI",
            # "BISARA ABASI JUMA",
            # "SHADIA SELEMANI RASHIDI",
            # "SHADIA MOHAMEDI HAMIDU",
            # "MARIAMU SHIJA ZABLONI",
            # "UMIY MUSA ALLY",
            # "RAHMA HAMZA RAMADHANI",
            # "LUCIA AMOSI HOBE",
            # "HADIJA NOTI RASHIDI",
            # "MWAJUMA MJUNGU SHABANI",
            # "NASWIYATI ABUU MSANTU",
            # "ZAITUNA HAMISI DONDO",
            # "MATHINA KASIMU RAMADHANI",
            # "ASANAINA RAMADHANI IDDI",
            # "WARDA KASSIMU YUSUPH",
            # "ASIA BAKARI RAMADHANI",
            # "MWAJABU ABUBAKARI HASANI",
            # "JASMINI OMARI KUNCHILI",
            # "MARIAMU ATHUMANI HUSENI",
            # "SHAMSIA RAMADHANI ATHUMANI",
            # "HALIMA IPALA RAMADHANI",
            # "THUWAIBA ATHUMANI NDULA",
            # "SAMIRA HASANI MOHAMEDI",
            # "ABDUL-LATIFU WAZIRI",
            # "ABDUL-AZIZ SEIFU",
            # "ABUNAIMU MUSTAFA",
            # "ABDUL-AZIZ ADAMU",
            # "HASANI ASHIRAFU",
            # "JAFARI IDDI",
            # "METHEW FESTO",
            # "MUHUTWARI RAMADHANI",
            # "MBARAKA ADAMU",
            # "MUSTAFA OMARI",
            # "SADAMU HASHIMU",
            # "SALIMU HASANI",
            # "SHABANI JUMA",
            # "TOMASI FESTO",
            # "YASIRI ALLY",
            # "TUMAINI SAMWELI",
            # "ANWARI RAMADHANI",
            # "ASHIRAFU JUMA",
            # "HAIDARI RAMADHANI",
            # "ASHIRAFU ALLY",
            # "YASIRI HASANI",
            # "MOHAMEDI RASHIDI",
            # "THABITI RAMADHANI",
            # "MOHAMEDI HAJI",
            # "HAMZA JUMA",
            # "SAMWELI KWASILEMA",
            # "ABDUL-AZIZI HASHIMU",
            # "SELEMANI HALIDI",
            # "MGANYIZI FAUSTINI SELESTINI", 
            # "ESTA EZAKIELI MBUTU", 
            # "HAWA BASHIRU HUSENI", 
            # "NASIBU ALLY MBUTU", 
            # "ASIAMU JUMA BIBA", 
            # "SALHA IDDI RAMADHANI", 
            # "LUCIA AMOSI HOBE", 
            # "UMRA WAZIRI HUSENI", 
        ]

        for name in names:
            student = Student(
                full_name=name,
                gender="F",  # placeholder, unaweza kuset baadaye
                dob=date(2008, 1, 1),  # placeholder DOB
                form=4,
                stream="A", # wote Form I B
                parent_name="UNKNOWN",
                parent_contact="0000000000",
            )
            student.save()

            self.stdout.write(
                self.style.SUCCESS(f"✅ {student.full_name} created with AdmNo: {student.admission_number}")
            )

        self.stdout.write(self.style.SUCCESS("🎉 Done! All Form I A students imported."))
