# Generated by Django 5.2.6 on 2026-01-10 07:16

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_group', models.CharField(choices=[('teachers', 'Teachers'), ('parents', 'Parents'), ('all', 'Everyone')], max_length=20)),
                ('is_correction', models.BooleanField(default=False, help_text='Check if this message corrects or invalidates a previous one.')),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, help_text='Upload PDF or Excel files only.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
