# Generated by Django 5.2.6 on 2026-01-20 15:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='sms_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='PDF or Excel only', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_correction',
            field=models.BooleanField(default=False),
        ),
    ]
